apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i653bkkjb-go 
  janus-idp.io/tekton: i653bkkjb-go
  backstage.io/kubernetes-id: i653bkkjb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i653bkkjb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml